In [34]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.offline as pyo
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly.subplots as subplots
import cufflinks as cf
%matplotlib inline
from plotly.offline import iplot
import plotly.graph_objs as go
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')
# !pip install cufflinks

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

###**Reading Files**###

In [35]:
ball=pd.read_csv('/content/drive/MyDrive/WiDS_Dataset/IPL_Ball_by_Ball_2008_2022.csv')
ball.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [36]:
matches=pd.read_csv('/content/drive/MyDrive/WiDS_Dataset/IPL_Matches_2008_2022.csv')
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [37]:
df=pd.merge(ball,matches,on='ID',how='right')
df.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

###**Pre-Processing Data**###

In [38]:
# Convert 'Date' column to datetime
df['date'] = pd.to_datetime(df['Date'])

# Sort DataFrame by 'date', 'innings', 'overs', and 'ballnumber'
df = df.sort_values(by=['date', 'innings', 'overs', 'ballnumber'])

# Reset the index after sorting
df = df.reset_index(drop=True)

# Display the first few rows of the DataFrame
df.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,date
0,335982,1,0,1,SC Ganguly,P Kumar,BB McCullum,legbyes,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
1,335982,1,0,2,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
2,335982,1,0,3,BB McCullum,P Kumar,SC Ganguly,wides,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
3,335982,1,0,4,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
4,335982,1,0,5,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18

In [39]:
df['Team1'].unique()

array(['Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype=object)

In [40]:
df=df.replace(['Pune Warriors','Rising Pune Supergiant','Delhi Daredevils'],['Rising Pune Supergiants','Rising Pune Supergiants','Delhi Capitals'])
df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,date
0,335982,1,0,1,SC Ganguly,P Kumar,BB McCullum,legbyes,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
1,335982,1,0,2,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
2,335982,1,0,3,BB McCullum,P Kumar,SC Ganguly,wides,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
3,335982,1,0,4,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
4,335982,1,0,5,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,1312200,2,17,3,DA Miller,R Ashwin,Shubman Gill,NaN,1,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022-05-29
225950,1312200,2,17,4,Shubman Gill,R Ashwin,DA Miller,NaN,0,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022-05-29
225951,1312200,2,17,5,Shubman Gill,R Ashwin,DA Miller,NaN,1,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022-05-29
225952,1312200,2,17,6,DA Miller,R Ashwin,Shubman Gill,NaN,2,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022-05-29
225953,1312200,2,18,1,Shubman Gill,OC McCoy,DA Miller,NaN,6,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,2022-05-29

In [41]:
df['year']=pd.DatetimeIndex(df['date']).year
df.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,date,year
0,335982,1,0,1,SC Ganguly,P Kumar,BB McCullum,legbyes,0,1,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18,2008
1,335982,1,0,2,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18,2008
2,335982,1,0,3,BB McCullum,P Kumar,SC Ganguly,wides,0,1,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18,2008
3,335982,1,0,4,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18,2008
4,335982,1,0,5,BB McCullum,P Kumar,SC Ganguly,NaN,0,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,2008-04-18,2008

In [42]:
columns = ['WonBy' , 'Margin' , 'Umpire1' , 'Umpire2' , 'batter' , 'non-striker' , 'bowler' , 'non_boundary' , 'kind' , 'player_out' , 'fielders_involved' , 'extra_type' , 'Player_of_Match', 'Venue' , 'City' ]
df1 = df.drop(columns = columns)
df1.head()

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,method,Team1Players,Team2Players,date,year
0,335982,1,0,1,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,NaN,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
1,335982,1,0,2,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,NaN,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
2,335982,1,0,3,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,NaN,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
3,335982,1,0,4,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,NaN,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
4,335982,1,0,5,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,NaN,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008

In [43]:
df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [44]:
df1['method']=df1['method'].fillna('Normal')
df1.head()

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,method,Team1Players,Team2Players,date,year
0,335982,1,0,1,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
1,335982,1,0,2,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
2,335982,1,0,3,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
3,335982,1,0,4,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
4,335982,1,0,5,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008

In [45]:
df1=df1.dropna()
df1.isnull().sum()

ID                  0
innings             0
overs               0
ballnumber          0
batsman_run         0
extras_run          0
total_run           0
isWicketDelivery    0
BattingTeam         0
Date                0
Season              0
MatchNumber         0
Team1               0
Team2               0
TossWinner          0
TossDecision        0
SuperOver           0
WinningTeam         0
method              0
Team1Players        0
Team2Players        0
date                0
year                0
dtype: int64

In [46]:

df1.head()

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,method,Team1Players,Team2Players,date,year
0,335982,1,0,1,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
1,335982,1,0,2,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
2,335982,1,0,3,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
3,335982,1,0,4,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
4,335982,1,0,5,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008

In [47]:
df1.reset_index(inplace=True)
df1.drop(columns=['index'],inplace=True)
df1.head()

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team2,TossWinner,TossDecision,SuperOver,WinningTeam,method,Team1Players,Team2Players,date,year
0,335982,1,0,1,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
1,335982,1,0,2,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
2,335982,1,0,3,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
3,335982,1,0,4,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008
4,335982,1,0,5,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Kolkata Knight Riders,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Normal,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,2008

###**One-Hot Encoding**###

In [48]:
dummy_toss=pd.get_dummies(df1['TossDecision'])
df_enc=pd.concat([df1,dummy_toss],axis='columns')
df_enc.drop(columns=['TossDecision','bat','year'],inplace=True) #the bat column does not provide any new information therefore dropped
#df_enc
dummy_method=pd.get_dummies(df1['method'])
df_enc=pd.concat([df_enc,dummy_method],axis=1)
df_enc.drop(columns=['method','Normal'],inplace=True)  #The normal column does not add any new value so dropping it along with the original column
df_enc.head()

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team1,Team2,TossWinner,SuperOver,WinningTeam,Team1Players,Team2Players,date,field,D/L
0,335982,1,0,1,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,N,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False
1,335982,1,0,2,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,N,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False
2,335982,1,0,3,0,1,1,0,Kolkata Knight Riders,2008-04-18,...,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,N,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False
3,335982,1,0,4,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,N,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False
4,335982,1,0,5,0,0,0,0,Kolkata Knight Riders,2008-04-18,...,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,N,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False

*CREATING* A NEW COLUMN WITH THE VALUE AS ID+BATTING TEAM WHICH WILL ACT AS THE ID FOR AN INNING

In [49]:

df_enc['id_inning']=df_enc['ID'].astype(str)+df_enc['BattingTeam']
df_enc.sample(10)

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run,isWicketDelivery,BattingTeam,Date,...,Team2,TossWinner,SuperOver,WinningTeam,Team1Players,Team2Players,date,field,D/L,id_inning
14615,392186,2,1,1,1,0,1,0,Kolkata Knight Riders,2009-04-21,...,Kolkata Knight Riders,Kolkata Knight Riders,N,Kolkata Knight Riders,"['RS Bopara', 'K Goel', 'IK Pathan', 'KC Sanga...","['BB McCullum', 'CH Gayle', 'BJ Hodge', 'SC Ga...",2009-04-21,True,True,392186Kolkata Knight Riders
55713,501259,1,6,3,0,0,0,0,Rising Pune Supergiants,2011-05-16,...,Deccan Chargers,Deccan Chargers,N,Deccan Chargers,"['JD Ryder', 'MK Pandey', 'SC Ganguly', 'RV Ut...","['S Sohal', 'S Dhawan', 'KC Sangakkara', 'JP D...",2011-05-16,True,False,501259Rising Pune Supergiants
122337,980901,2,5,1,0,0,0,0,Rising Pune Supergiants,2016-04-09,...,Rising Pune Supergiants,Mumbai Indians,N,Rising Pune Supergiants,"['LMP Simmons', 'RG Sharma', 'HH Pandya', 'JC ...","['AM Rahane', 'F du Plessis', 'KP Pietersen', ...",2016-04-09,False,False,980901Rising Pune Supergiants
86274,598038,1,10,3,2,0,2,0,Chennai Super Kings,2013-04-30,...,Chennai Super Kings,Chennai Super Kings,N,Chennai Super Kings,"['RV Uthappa', 'AJ Finch', 'TL Suman', 'Yuvraj...","['MEK Hussey', 'WP Saha', 'SK Raina', 'S Badri...",2013-04-30,False,False,598038Chennai Super Kings
188206,1216494,2,2,7,0,0,0,0,Royal Challengers Bangalore,2020-10-21,...,Royal Challengers Bangalore,Kolkata Knight Riders,N,Royal Challengers Bangalore,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'T B...","['D Padikkal', 'AJ Finch', 'Gurkeerat Singh', ...",2020-10-21,False,False,1216494Royal Challengers Bangalore
193345,1254058,1,16,3,1,0,1,0,Mumbai Indians,2021-04-09,...,Royal Challengers Bangalore,Royal Challengers Bangalore,N,Royal Challengers Bangalore,"['RG Sharma', 'CA Lynn', 'SA Yadav', 'Ishan Ki...","['Washington Sundar', 'V Kohli', 'RM Patidar',...",2021-04-09,True,False,1254058Mumbai Indians
82661,598022,2,6,1,0,0,0,0,Chennai Super Kings,2013-04-20,...,Chennai Super Kings,Kolkata Knight Riders,N,Chennai Super Kings,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",2013-04-20,False,False,598022Chennai Super Kings
86332,598038,1,19,6,6,0,6,0,Chennai Super Kings,2013-04-30,...,Chennai Super Kings,Chennai Super Kings,N,Chennai Super Kings,"['RV Uthappa', 'AJ Finch', 'TL Suman', 'Yuvraj...","['MEK Hussey', 'WP Saha', 'SK Raina', 'S Badri...",2013-04-30,False,False,598038Chennai Super Kings
167704,1175369,1,15,4,2,0,2,0,Royal Challengers Bangalore,2019-04-02,...,Rajasthan Royals,Rajasthan Royals,N,Rajasthan Royals,"['V Kohli', 'PA Patel', 'AB de Villiers', 'SO ...","['AM Rahane', 'JC Buttler', 'SPD Smith', 'RA T...",2019-04-02,True,False,1175369Royal Challengers Bangalore
6036,336007,1,17,1,1,0,1,0,Chennai Super Kings,2008-05-06,...,Deccan Chargers,Deccan Chargers,N,Deccan Chargers,"['PA Patel', 'SP Fleming', 'S Anirudha', 'SK R...","['AC Gilchrist', 'HH Gibbs', 'SB Styris', 'RG ...",2008-05-06,True,False,336007Chennai Super Kings

In [50]:
list=df_enc['id_inning'].unique()
len(list)

# list=df_enc['Date'].unique()
# len(list)

1892

In [51]:
#Total run column in the df_enc is only giving us the runs scored on that particular ball, so to get the runs scored in an innings we need
# to first group each innings column and then sum the total run..

numeric_columns = df_enc.select_dtypes(include=['number']).columns.tolist()
numeric_columns.append('id_inning')  # Include the grouping column
# print(numeric_columns)
# Perform groupby and sum only on numeric columns
df_grouped = df_enc[numeric_columns].groupby(by=['id_inning']).sum()
# print(df_grouped)
# Extract the 'total_run' column and reset the index
df_copy = df_grouped[['total_run']].reset_index()

# Display the first few rows
df_copy.head()
# df_copy.sample(10)

                            id_inning  total_run
0  1082591Royal Challengers Bangalore        172
1          1082591Sunrisers Hyderabad        207
2               1082592Mumbai Indians        184
3      1082592Rising Pune Supergiants        187
4                1082593Gujarat Lions        183

In [52]:
#Now we are going to merge the total runs scored in the initial in our initial df_enc

data=pd.merge(left=df_enc,right=df_copy,on='id_inning',how='right')
data.head(6)

,ID,innings,overs,ballnumber,batsman_run,extras_run,total_run_x,isWicketDelivery,BattingTeam,Date,...,TossWinner,SuperOver,WinningTeam,Team1Players,Team2Players,date,field,D/L,id_inning,total_run_y
0,1082591,2,0,1,1,0,1,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
1,1082591,2,0,2,0,0,0,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
2,1082591,2,0,3,0,0,0,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
3,1082591,2,0,4,2,0,2,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
4,1082591,2,0,5,4,0,4,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
5,1082591,2,0,6,4,0,4,0,Royal Challengers Bangalore,2017-04-05,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172

In [53]:
# Now we are going to covert each ball as overs dot ball number e.g 1.2, 2.5,..

data['overs']=data['overs']+(data['ballnumber'])/10
data.drop(columns=['ballnumber'],inplace=True)
data.head(12)

,ID,innings,overs,batsman_run,extras_run,total_run_x,isWicketDelivery,BattingTeam,Date,Season,...,TossWinner,SuperOver,WinningTeam,Team1Players,Team2Players,date,field,D/L,id_inning,total_run_y
0,1082591,2,0.1,1,0,1,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
1,1082591,2,0.2,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
2,1082591,2,0.3,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
3,1082591,2,0.4,2,0,2,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
4,1082591,2,0.5,4,0,4,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
5,1082591,2,0.6,4,0,4,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
6,1082591,2,1.1,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
7,1082591,2,1.2,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
8,1082591,2,1.3,1,0,1,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
9,1082591,2,1.4,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
10,1082591,2,1.5,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172
11,1082591,2,1.6,0,0,0,0,Royal Challengers Bangalore,2017-04-05,2017,...,Royal Challengers Bangalore,N,Sunrisers Hyderabad,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['CH Gayle', 'Mandeep Singh', 'TM Head', 'KM J...",2017-04-05,True,False,1082591Royal Challengers Bangalore,172

###**Adding runs and wickets at every instant of the match**###

In [54]:
# Now we going to add runs and wickets at every instant of the match

# Create an empty DataFrame
data_final = pd.DataFrame()
# Here list is basically an array of the id_inning representing each innings
for id in list:
    inning_data = data[data['id_inning'] == id]

    # Calculate cumulative sums
    cum_total = inning_data['total_run_x'].cumsum()
    cum_wicket = inning_data['isWicketDelivery'].cumsum()

    # Add cumulative sums to DataFrame
    inning_data['runs'] = cum_total
    inning_data['wickets'] = cum_wicket

    # Use pd.concat to append the DataFrame
    data_final = pd.concat([data_final, inning_data], ignore_index=True)

data_final.head(20)

,ID,innings,overs,batsman_run,extras_run,total_run_x,isWicketDelivery,BattingTeam,Date,Season,...,WinningTeam,Team1Players,Team2Players,date,field,D/L,id_inning,total_run_y,runs,wickets
0,335982,1,0.1,0,1,1,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,1,0
1,335982,1,0.2,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,1,0
2,335982,1,0.3,0,1,1,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,2,0
3,335982,1,0.4,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,2,0
4,335982,1,0.5,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,2,0
5,335982,1,0.6,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,2,0
6,335982,1,0.7,0,1,1,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,3,0
7,335982,1,1.1,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,3,0
8,335982,1,1.2,4,0,4,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,7,0
9,335982,1,1.3,4,0,4,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,11,0
10,335982,1,1.4,6,0,6,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,17,0
11,335982,1,1.5,4,0,4,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,21,0
12,335982,1,1.6,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,21,0
13,335982,1,2.1,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,21,0
14,335982,1,2.2,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,21,0
15,335982,1,2.3,0,1,1,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,22,0
16,335982,1,2.4,4,0,4,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,26,0
17,335982,1,2.5,1,0,1,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,27,0
18,335982,1,2.6,0,0,0,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,27,0
19,335982,1,3.1,0,5,5,0,Kolkata Knight Riders,2008-04-18,2007/08,...,Kolkata Knight Riders,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,335982Kolkata Knight Riders,222,32,0

###**Label Encoding for teams**###

In [55]:
from sklearn import preprocessing
p=preprocessing.LabelEncoder()

In [56]:
data_final['Team1'].unique()

array(['Royal Challengers Bangalore', 'Delhi Capitals', 'Kings XI Punjab',
       'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Rising Pune Supergiants', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Punjab Kings', 'Lucknow Super Giants', 'Gujarat Titans'],
      dtype=object)

In [57]:
team_dict = {'Mumbai Indians':12, 'Chennai Super Kings':11, 'Rajasthan Royals':10, 'Kolkata Knight Riders':9, 'Kings XI Punjab':8,
             'Sunrisers Hyderabad':7, 'Delhi Capitals':6, 'Royal Challengers Bangalore':5, 'Gujarat Lions':4, 'Deccan Chargers':3,
             'Rising Pune Supergiants':2, 'Kochi Tuskers Kerala':1
             }

In [58]:
temp=data_final.copy()
temp['Team1']=temp.Team1.map(team_dict)
temp['Team2']=temp.Team2.map(team_dict)
temp['WinningTeam']=temp.WinningTeam.map(team_dict)
temp['TossWinner']=temp.TossWinner.map(team_dict)
temp['BattingTeam']=temp.BattingTeam.map(team_dict)
temp.head()
temp.isnull().sum()

ID                     0
innings                0
overs                  0
batsman_run            0
extras_run             0
total_run_x            0
isWicketDelivery       0
BattingTeam         7199
Date                   0
Season                 0
MatchNumber            0
Team1               7917
Team2               6324
TossWinner          6366
SuperOver              0
WinningTeam         8277
Team1Players           0
Team2Players           0
date                   0
field                  0
D/L                    0
id_inning              0
total_run_y            0
runs                   0
wickets                0
dtype: int64

In [59]:
temp.drop(columns=['id_inning','extras_run','total_run_x','isWicketDelivery','batsman_run'],inplace=True)
temp.head()

,ID,innings,overs,BattingTeam,Date,Season,MatchNumber,Team1,Team2,TossWinner,SuperOver,WinningTeam,Team1Players,Team2Players,date,field,D/L,total_run_y,runs,wickets
0,335982,1,0.1,9.0,2008-04-18,2007/08,1,5.0,9.0,5.0,N,9.0,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,1,0
1,335982,1,0.2,9.0,2008-04-18,2007/08,1,5.0,9.0,5.0,N,9.0,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,1,0
2,335982,1,0.3,9.0,2008-04-18,2007/08,1,5.0,9.0,5.0,N,9.0,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0
3,335982,1,0.4,9.0,2008-04-18,2007/08,1,5.0,9.0,5.0,N,9.0,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0
4,335982,1,0.5,9.0,2008-04-18,2007/08,1,5.0,9.0,5.0,N,9.0,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0

In [60]:
X=temp.copy()
y_winner=X.iloc[:,-7].values#Accessing winningTeam column
y_winner=y_winner.reshape(-1,1)#Creating a column vector for storing the winner
# print(y_winner)
X.drop(columns=['WinningTeam','ID','Date', 'Season'],inplace=True)
X.isnull().sum()

innings            0
overs              0
BattingTeam     7199
MatchNumber        0
Team1           7917
Team2           6324
TossWinner      6366
SuperOver          0
Team1Players       0
Team2Players       0
date               0
field              0
D/L                0
total_run_y        0
runs               0
wickets            0
dtype: int64

In [61]:
X.head()

,innings,overs,BattingTeam,MatchNumber,Team1,Team2,TossWinner,SuperOver,Team1Players,Team2Players,date,field,D/L,total_run_y,runs,wickets
0,1,0.1,9.0,1,5.0,9.0,5.0,N,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,1,0
1,1,0.2,9.0,1,5.0,9.0,5.0,N,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,1,0
2,1,0.3,9.0,1,5.0,9.0,5.0,N,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0
3,1,0.4,9.0,1,5.0,9.0,5.0,N,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0
4,1,0.5,9.0,1,5.0,9.0,5.0,N,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",2008-04-18,True,False,222,2,0

In [62]:
y=X.iloc[:,-3].values#Extracting the total runs column from the dataframe most important feature for predicting the winner
y=y.reshape(-1,1)#Reshaping the numpy array

#y=pd.DataFrame(data=y[0:,0],columns=['runs_total'])
columns_to_drop = [
    'total_run_y', 'MatchNumber', 'SuperOver', 'Team1Players', 'Team2Players',
    'date', 'BattingTeam', 'Team2', 'Team1', 'TossWinner'
]

# Check which columns are present in the DataFrame
existing_columns_to_drop = [col for col in columns_to_drop if col in X.columns]
X.drop(columns=existing_columns_to_drop, inplace=True)
print(y)
print(X)

[[222]
 [222]
 [222]
 ...
 [133]
 [133]
 [133]]
        innings  overs  field    D/L  runs  wickets
0             1    0.1   True  False     1        0
1             1    0.2   True  False     1        0
2             1    0.3   True  False     2        0
3             1    0.4   True  False     2        0
4             1    0.5   True  False     2        0
...         ...    ...    ...    ...   ...      ...
225577        2   17.3  False  False   124        3
225578        2   17.4  False  False   124        3
225579        2   17.5  False  False   125        3
225580        2   17.6  False  False   127        3
225581        2   18.1  False  False   133        3

[225582 rows x 6 columns]

###**Custom Accuracy Model**###

In [63]:
def custom_accu(y_test,y_pred,thresh):

  correct=0
  length=len(y_pred)
  for i in range(0,length):

    if(abs(y_test[i]-y_pred[i])<=thresh):

      correct=correct+1
  return((correct/length)*100)

###**SVM Model**###

In [33]:
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error

# Assuming X and y are already defined and preprocessed
# Reshape y to be a 1D array
y = y.ravel()

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)

# Define column transformer for preprocessing
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Define the parameter grid for SVR
param_grid = {
    'svr__C': [0.1, 1, 10],
    'svr__epsilon': [0.1, 0.2, 0.5],
    'svr__kernel': ['linear', 'rbf', 'poly']
}

# Create a pipeline with preprocessing and SVR
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('svr', SVR())
])

# Setup GridSearchCV with the pipeline
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train.ravel())

# Best parameters and model
best_svr = grid_search.best_estimator_

# Predict with the best model
y_predict = best_svr.predict(X_test)

# Calculate mean squared error and custom accuracy
mse = mean_squared_error(y_test, y_predict)
custom_accuracy = custom_accu(y_test, y_predict, 10)

print(f'Best parameters: {grid_search.best_params_}')
print(f'Custom accuracy is: {custom_accuracy}%')
print(f'Mean Squared Error: {mse}')

# Optional: Perform cross-validation on the full data
cv_scores = cross_val_score(best_svr, X, y.ravel(), cv=3, scoring='neg_mean_squared_error')
print(f'Cross-validated MSE: {-np.mean(cv_scores)}')

Fitting 3 folds for each of 27 candidates, totalling 81 fits

KeyboardInterrupt:

###**Linear Regression with Ridge and Lasso Regularization**###

In [64]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

# Assuming X and y are already defined and preprocessed
# Reshape y to be a 1D array
y = y.ravel()

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)

# Define column transformer for preprocessing
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create pipelines for Linear Regression, Ridge, and Lasso
linear_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('regressor', LinearRegression())
])

ridge_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('regressor', Ridge(alpha=1.0))
])

lasso_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('regressor', Lasso(alpha=0.1))
])

# Fit and evaluate the Linear Regression model
linear_pipeline.fit(X_train, y_train)
y_pred = linear_pipeline.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
custom_accuracy = custom_accu(y_test, y_pred, 10)

print('Linear Regression:')
print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R² Score: {r2}')
print(f'Custom accuracy is: {custom_accuracy}%')

# Perform cross-validation for Linear Regression
cv_scores = cross_val_score(linear_pipeline, X, y, cv=5, scoring='neg_mean_squared_error')
print(f'Linear Regression Cross-validated MSE: {-np.mean(cv_scores)}')

# Fit and evaluate the Ridge model
ridge_pipeline.fit(X_train, y_train)
y_pred_ridge = ridge_pipeline.predict(X_test)

ridge_mae = mean_absolute_error(y_test, y_pred_ridge)
ridge_mse = mean_squared_error(y_test, y_pred_ridge)
ridge_r2 = r2_score(y_test, y_pred_ridge)
ridge_custom_accuracy = custom_accu(y_test, y_pred_ridge, 12)

print('\nRidge Regression:')
print(f'Mean Absolute Error: {ridge_mae}')
print(f'Mean Squared Error: {ridge_mse}')
print(f'R² Score: {ridge_r2}')
print(f'Custom accuracy is: {ridge_custom_accuracy}%')

# Perform cross-validation for Ridge Regression
cv_scores_ridge = cross_val_score(ridge_pipeline, X, y, cv=5, scoring='neg_mean_squared_error')
print(f'Ridge Regression Cross-validated MSE: {-np.mean(cv_scores_ridge)}')

# Fit and evaluate the Lasso model
lasso_pipeline.fit(X_train, y_train)
y_pred_lasso = lasso_pipeline.predict(X_test)

lasso_mae = mean_absolute_error(y_test, y_pred_lasso)
lasso_mse = mean_squared_error(y_test, y_pred_lasso)
lasso_r2 = r2_score(y_test, y_pred_lasso)
lasso_custom_accuracy = custom_accu(y_test, y_pred_lasso, 12)

print('\nLasso Regression:')
print(f'Mean Absolute Error: {lasso_mae}')
print(f'Mean Squared Error: {lasso_mse}')
print(f'R² Score: {lasso_r2}')
print(f'Lasso Custom accuracy is: {lasso_custom_accuracy}%')

# Perform cross-validation for Lasso Regression
cv_scores_lasso = cross_val_score(lasso_pipeline, X, y, cv=5, scoring='neg_mean_squared_error')
print(f'Lasso Regression Cross-validated MSE: {-np.mean(cv_scores_lasso)}')

Linear Regression:
Mean Absolute Error: 16.21362521263093
Mean Squared Error: 478.8889257658986
R² Score: 0.45285596774453196
Custom accuracy is: 43.157698752560044%
Linear Regression Cross-validated MSE: 486.4742011353995

Ridge Regression:
Mean Absolute Error: 16.213661021538837
Mean Squared Error: 478.88956251282985
R² Score: 0.45285524024329993
Custom accuracy is: 50.11038114743197%
Ridge Regression Cross-validated MSE: 486.4745800593967

Lasso Regression:
Mean Absolute Error: 16.2568348225024
Mean Squared Error: 481.17884781369906
R² Score: 0.450239667564317
Lasso Custom accuracy is: 50.07403072940216%
Lasso Regression Cross-validated MSE: 488.7218284489778

###**Random Forest Regressor**###

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.impute import SimpleImputer
import numpy as np

# Assuming X and y are already defined and preprocessed
# Reshape y to be a 1D array
y = y.ravel()

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)

# Define column transformer for preprocessing
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Define the RandomForestRegressor with GridSearchCV
rfr = RandomForestRegressor(random_state=1)
param_grid = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4]
}

# Create preprocessing and training pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', rfr)
])

# Setup GridSearchCV with the pipeline
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=3, n_jobs=2, verbose=2)
grid_search.fit(X_train, y_train)

# Best parameters and model
best_model = grid_search.best_estimator_

# Predict with the best model
y_pred = best_model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
custom_accuracy = custom_accu(y_test, y_pred, 10)

print(f'Best parameters: {grid_search.best_params_}')
print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')
print(f'R² Score: {r2}')
print(f'Custom accuracy is: {custom_accuracy}%')

# Optional: Perform cross-validation on the full data
cv_scores = cross_val_score(best_model, X, y, cv=3, scoring='neg_mean_squared_error')
print(f'Cross-validated MSE: {-np.mean(cv_scores)}')

Fitting 3 folds for each of 108 candidates, totalling 324 fits

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning:

A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.